// Builds web/vendor/crux-render.js from web-src/ (renderer, components, highlight.js, yaml).
// Run after changing web-src/ or the answer-me-with-html skill: npm run build:web
// The output is committed so building the Go binary needs no Node.
import { build } from "esbuild";
import { fileURLToPath } from "node:url";

const stub = fileURLToPath(new URL("../web-src/stub-node.js", import.meta.url));
await build({
  entryPoints: [fileURLToPath(new URL("../web-src/index.js", import.meta.url))],
  outfile: fileURLToPath(new URL("../web/vendor/crux-render.js", import.meta.url)),
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  legalComments: "none",
  banner: { js: "// crux renderer — generated by scripts/build-web.mjs from web-src/. Do not edit." },
  plugins: [{ name: "node-stub", setup(b) { b.onResolve({ filter: /^node:/ }, () => ({ path: stub })); } }],
  logLevel: "warning",
});
console.log("✓ web/vendor/crux-render.js");
